/* becode/javascript
 *
 * /03-colors/03-change-bcg-three/script.js - 3.3: couleur de fond (3)
 *
 * coded by leny@BeCode
 * started at 26/10/2018
 */

// NOTE: don't focus on the existing code structure for now.
// You will have time to focus on it later.

(function() {

    // the click event which triggers the function to run
    document.getElementById("run").addEventListener("click", function () {



    // the random hex code generator
    function r() { return Math.floor(Math.random() * 255) }

    const color = 'rgb(' + r() + "," + r() + "," + r() + ')';



    // checking the code logs random colors to the console
    console.log(color);



    // make the document take the color generated by the random generator
    document.body.style.backgroundColor = color; 
    });

})();
